apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: emr-eks-dev
  region: ap-northeast-2
  version: "1.24"

vpc:
  subnets:
    private:
      ap-northeast-2a: { id: subnet-05b89fde393057ce3 }
      ap-northeast-2b: { id: subnet-050e5d124c1f2e93d }
      ap-northeast-2c: { id: subnet-07a3958e782d1df2c }

iam:
  withOIDC: true

managedNodeGroups:
  - name: eks-worker
    labels: { role: workers }
    tags:
      nodegroup-role: worker
    instanceName: eks-worker
    instanceType: m5.large
    minSize: 1
    desiredCapacity: 2
    maxSize: 3
    privateNetworking: true
    availabilityZones: ["ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"]