apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: emr-eks-dev
  region: ap-northeast-2

managedNodeGroups:
- name: test-ng
  labels: { role: workers }
  minSize: 1
  desiredCapacity: 2
  maxSize: 3
  privateNetworking: true
  instanceType: t3.large
  ssh:
    enableSsm: true
  availabilityZones: ["ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"]