apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
  labels:
    app: karpenter
    version: v0.25.0
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: ["t", "c", "g"]
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values: ["2"]
  limits:
    resources:
      cpu: 100
      memory: 100Gi
      nvia.com/gpu: 3
  providerRef:
    name: default-nodetemplate
  ttlSecondsAfterEmpty: 30
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default-nodetemplate
  labels:
    app: karpenter
    version: v0.25.0
spec:
  amiFamily: AL2
  subnetSelector:
    karpenter.sh/discovery: "eks-dev-temp"
  securityGroupSelector:
    karpenter.sh/discovery: "eks-dev-temp"
  blockDeviceMappings:
    - deviceName: /dev/xvda # root Volume to store OS Binaries
      ebs:
        volumeType: gp2 # EBS Volume Type
        volumeSize: 16Gi # Size of the disk
        deleteOnTermination: true # Disk Retention Policy
